export const MAX_MOBILE_WIDTH = 576;

export const PAGE = {
    BENCHMARK_GPU: "BENCHMARK_GPU",
    BENCHMARK_CPU: "BENCHMARK_CPU",
    STRESS_GPU: "STRESS_GPU",
    STRESS_CPU: "STRESS_CPU",
    RECORDS: "RECORDS",
};
